---
- hosts: all
  become: true
  tasks:
  # - name: update distribution
  #   apt:
  #     update_cache: yes
  # - name: install git
  #   apt:
  #     name:
  #       - git
  #       - nodejs
  #       - npm
  #     update_cache: yes
  - name: file configuration copy
    copy: 
      src: conf/
      dest: /

#si on met le update_cache à la fin de install git alors on commente la partie update distribution